plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  Abilities-Qualities-Values.md
  Building-Products-and-Startups-OKRs.md
  Conflict-Prevention-Resolution.md
  Culture.md
  Diversity-and-Gender.md
  EMCheatsheet.md
  Engg-Manager-README.md
  Firing.md
  For-Developers-Teamwork-TechDebt.md
  Giving-Feedback-Praise-and-Advice.md
  Hiring-and-Interviewing.md
  Influence-Delegation-and-Decision-Making.md
  Leader-List.md
  Leadership-Forums.md
  Leadership-Media.md
  Leadership-Philosophies-and-Styles.md
  Leadership.md
  Leading-Leaders.md
  Meetings-and-Time-Management.md
  Motivation-Retention.md
  Onboarding.md
  One-on-Ones.md
  People-Ops-Perf-Reviews-and-Goal-setting.md
  Personality.md
  Postmortems-Retrospectives.md
  ProductManagement.md
  README.md
  Scalability.md
  Transitioning-to-Management.md
  VPCheatsheet.md
  code-of-conduct.md
  interview.md
