plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  Engg-Manager-README.md
  Leadership.md
  Personality.md
  Scalability.md
  ProductManagement.md
  EMCheatsheet.md
  VPCheatsheet.md
